### ISSUE TITLE
Add classes to index

### ISSUE THREAD

**Issue by aaronmaynard** [aaronmaynard/Skyrim-Perk-Utility#12]
## first-timers-only

This issue is tagged :octocat: first-timers-only. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Thank you for your help ❤️

### Issue:

Your task is to add classes to the [index.html](https://github.com/aaronmaynard/Skyrim-Perk-Utility/blob/master/index.html "Located in root of repository") document of the repository.  These classes will be used for further implementation to enhance the user experience on the project which you can visit [here](https://aaronmaynard.github.io/Skyrim-Perk-Utility). You will be adding <b>four classes</b> to the document. The four classes will consist of <b>three</b> types; `cDefault`, `cCrosshair` and `cDownload`. 

`cDefault` will need to be added to the `<div id="cursorMod">` element, `cCrosshair` added to the canvas, and `cDownload` added to the two download spans. When adding a class to an element, use the following syntax: 
``` 
<element class="className" id="idName">
    <foo>
        <p>Hello, World!</p>
    </foo>
</element>
```

### Contributing:

-  Comment in this issue that you would like to do it.
-  Open the Skyrim-Perk-Utility GitHub page and click the ★ Star and then ⑂ Fork buttons.
-  Once you've made sure all your changes work correctly and committed all your changes,
-  Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/Skyrim-Perk-Utility) and create a pull request for your changes.
-  Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #12)
-  Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community.
If you need any help, feel free to ask below. We are always happy to help 😄

**Comment by 3sanket3** [comment]
Hi, I will do this as my first PR.

Thanks for giving chance.

**Comment by 3sanket3** [comment]
Oops, @aviral19  already did it :+1:
