### ISSUE TITLE
Enable custom cursor

### ISSUE THREAD

**Issue by aaronmaynard** [aaronmaynard/Skyrim-Perk-Utility#13]
## first-timers-only

This issue is tagged :octocat: first-timers-only. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Thank you for your help ❤️

### Issue:

Your task is to add the styling elements for the [custom cursors](https://github.com/aaronmaynard/Skyrim-Perk-Utility/tree/master/cursor "Check out the cursors here") recently uploaded to the repository.  This needs to be done to both [style.css](https://github.com/aaronmaynard/Skyrim-Perk-Utility/blob/master/css/style.css "Located in root of repository") and [help.css](https://github.com/aaronmaynard/Skyrim-Perk-Utility/blob/master/css/help.css "Located in root of repository").  For <b>style.css</b> you will add elements for the classes `.cDefault`, `.cCrosshair` and `.cDownload`.  You add only `.cDefault` in <b>help.css</b>.  Add the styling elements for type <i>class</i> at the end of the documents, and use the appropriate syntax:
```
.class{
    cursor: url(https://aaronmaynard.github.io/Skyrim-Perk-Utility/cursor/[CURSOR_FILE.cur]), [CURSORTYPE];
}
```
The three types of cursors we will be implementing are `default`, `crosshair` and `pointer`.

Don't forget to add an endLine (Press Enter) at the end of the document.

### Contributing:

-  Comment in this issue that you would like to do it.
-  Open the Skyrim-Perk-Utility GitHub page and click the ★ Star and then ⑂ Fork buttons.
-  Once you've made sure all your changes work correctly and committed all your changes,
-  Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/Skyrim-Perk-Utility) and create a pull request for your changes.
-  Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #13)
-  Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community.
If you need any help, feel free to ask below. We are always happy to help 😄

**Comment by VanheeArne** [comment]
Hi, i'll try and fix this issue :) !
