### ISSUE TITLE
Add the ability to share build via link

### ISSUE THREAD

**Issue by aaronmaynard** [aaronmaynard/Skyrim-Perk-Utility#16]
# 🥇  first-timers-only

This issue is tagged :octocat: first-timers-only. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Thank you for your help ❤️

## 📋  Issue:

You will be adding an alternate option to saving the script generated by the user via the graphical interface.  This is pretty simple... you will be creating a button that will be used to grab the window location (URL) and allowing them to easily share their build with their friends via social media or other means.  This is laying the foundation for what will later be URL shortening.  Apply your changes to [index.html](https://github.com/aaronmaynard/Skyrim-Perk-Utility/blob/master/index.html) located in the root directory.

#### 🍎  Approach:
Add this button to the `<div class="dropdown-content">` element.  Follow the current formula for the interface by using a `<span>` element and the appropriate `class="className"`.  The text should read: "<b style="color:orange;">NEW </b>Share Online", without quotes, and "new" being in `color:orange`. When clicking on the button the user should be prompted to "Copy this link to share your build:" and be given the URL generated by the canvas.

###### [Inline Styling](https://www.w3schools.com/html/html_css.asp "w3schools tutorial"):
`<p style="color:blue;">This is a Styled Paragraph</p>` 
###### [Browser Prompting](https://www.w3schools.com/jsref/met_win_prompt.asp "w3schools tutorial"):
`onclick="prompt(text, defaultText)"`
###### [Element Classes](https://www.w3schools.com/html/html_classes.asp "w3schools tutorial"):
`<element class="someClass">Some Stuff</element>`
###### [JavaScript Window Location](https://www.w3schools.com/js/js_window_location.asp "w3schools tutorial"):
`window.location.assign` loads a new document  
`window.location.hostname` returns the domain name of the web host  
`window.location.href` returns the href (URL) of the current page  
`window.location.pathname` returns the path and filename of the current page  
`window.location.protocol` returns the web protocol used (http or https)  

## 👥  Contributing:

-  Comment in this issue that you would like to do it.
-  Open the Skyrim-Perk-Utility GitHub page and click the ★ Star and then ⑂ Fork buttons.
-  Once you've made sure all your changes work correctly and committed all your changes,
-  Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/Skyrim-Perk-Utility) and create a pull request for your changes.
-  Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #16)
-  Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

## 🆘  Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community.
If you need any help, feel free to ask below. We are always happy to help 😄

**Comment by pacbac** [comment]
Hi, can I start to try working on this?

**Comment by aaronmaynard** [comment]
@pacbac go for it! Good luck 😄
