### ISSUE TITLE
Add webpage for project

### ISSUE THREAD

**Issue by aaronmaynard** [aaronmaynard/Skyrim-Perk-Utility#20]
## 📦  Project: Ordinator Implementation

This issue is tied to the respective [project page](https://github.com/aaronmaynard/Skyrim-Perk-Utility/projects/1) and will be automatically sorted.  For more information on this project, [click here](https://github.com/aaronmaynard/Skyrim-Perk-Utility/tree/master/project/ordinator_implementation).   
❤️ Thanks for helping!

## 📋  Issue:

We are currently in the process of adding support for the ordinator mod.  But we still need a place to build.  Your task to to take the main [index.html](https://github.com/aaronmaynard/Skyrim-Perk-Utility/blob/master/index.html) located in root directory, make a copy of it called `ordinator.html`, and change the script src  
`<script type="text/javascript" src="js/data.js"></script>`  
to  
`<script type="text/javascript" src="js/data_ordinator.js"></script>`.

Thats it!  
Good luck!

## 👥  Contributing:

-  Comment in this issue that you would like to do it.
-  Open the Skyrim-Perk-Utility GitHub page and click the ★ Star and then ⑂ Fork buttons.
-  Once you've made sure all your changes work correctly and committed all your changes,
-  Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/Skyrim-Perk-Utility) and create a pull request for your changes.
-  Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #20)
-  Please <b>do not fix more than one issue at a time</b>. Your pull request should only fix what is described in this issue.

## 🆘  Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community.
If you need any help, feel free to ask below. We are always happy to help 😄

**Comment by prinzpiuz** [comment]
May I try
