### ISSUE TITLE
Add nodes to data_ordinator.js

### ISSUE THREAD

**Issue by aaronmaynard** [aaronmaynard/Skyrim-Perk-Utility#22]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request

**Description**:

Add the nodes to the data_ordinator.js.  This will make it easier for people to edit / modify the node position on the canvas.  

**Expected Behavior**:

N/A

**Actual Behavior**:

N/A

**Steps to Reproduce**:

If relevant, please include screenshots and logs.

**Screenshots (if any)**:

**Would you like to work on this issue?**
- [ ] Yes
- [X] No

**Comment by evalmay15** [comment]
Working on it. 👍

**Comment by evalmay15** [comment]
To be continued...

**Comment by aaronmaynard** [comment]
Closing the issue as we are going about this a different way
