### ISSUE TITLE
Add information in the help section

### ISSUE THREAD

**Issue by aaronmaynard** [aaronmaynard/Skyrim-Perk-Utility#29]
## first-timers-only

This issue is tagged :octocat: first-timers-only. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Thank you for your help ❤️
❤️ Thanks for helping!

## 📋  Issue:

We are currently in the process of adding support for the ordinator mod! With that said, some people may experience issue running our script if they are not sure what to do about perk ID's that look like `__0148FE1.`  To help with this you are going to add a section to our help page.  Use the text before the "for example:" in the [Note about Perk ID's](https://github.com/aaronmaynard/Skyrim-Perk-Utility/tree/master/project/ordinator_implementation) section. After, provide a link, using anchor tags, to that very page so they can see a more detailed description.
 
Good luck!

## 👥  Contributing:

-  Comment in this issue that you would like to do it.
-  Open the Skyrim-Perk-Utility GitHub page and click the ★ Star and then ⑂ Fork buttons.
-  Once you've made sure all your changes work correctly and committed all your changes,
-  Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/Skyrim-Perk-Utility) and create a pull request for your changes.
-  Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #29)
-  Please <b>do not fix more than one issue at a time</b>. Your pull request should only fix what is described in this issue.

## 🆘  Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community.
If you need any help, feel free to ask below. We are always happy to help 😄

**Comment by lyrahalden** [comment]
Hi! Can I work on this?

**Comment by lyrahalden** [comment]
I submitted my PR. Lmk if I have done it right and if the change I made was what you had in mind!
