### ISSUE TITLE
Move PULL_REQUEST_TEMPLATE and ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by aaronmaynard** [aaronmaynard/Skyrim-Perk-Utility#30]
## first-timers-only

This issue is tagged :octocat: first-timers-only. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Thank you for your help ❤️
❤️ Thanks for helping!

## 📋  Issue:

To aid in clutter control, please move [PULL_REQUEST_TEMPLATE](https://github.com/aaronmaynard/Skyrim-Perk-Utility/blob/master/docs/PULL_REQUEST_TEMPLATE.md) and [ISSUE_TEMPLATE](https://github.com/aaronmaynard/Skyrim-Perk-Utility/blob/master/docs/ISSUE_TEMPLATE.md) to the root directory.  You can simply copy the raw data and re-create the files in the root Skyrim-Perk-Utility if you see fit. After you have done so, delete the ones located in [docs](https://github.com/aaronmaynard/Skyrim-Perk-Utility/tree/master/docs) folder.  Please complete these in one pull request.
 
Good luck!

## 👥  Contributing:

-  Comment in this issue that you would like to do it.
-  Open the Skyrim-Perk-Utility GitHub page and click the ★ Star and then ⑂ Fork buttons.
-  Once you've made sure all your changes work correctly and committed all your changes,
-  Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/Skyrim-Perk-Utility) and create a pull request for your changes.
-  Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #30)
-  Please <b>do not fix more than one issue at a time</b>. Your pull request should only fix what is described in this issue.

## 🆘  Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community.
If you need any help, feel free to ask below. We are always happy to help 😄

**Comment by mukisankaran** [comment]
Hi, I'd like to work on this. I will disclose though that this would be my second PR on Github. The first PR I opened was for another project a few months ago but it was never reviewed by the maintainers of that project, so I don't consider it as a contribution. If this is okay, please review my PR. Thanks.
