### ISSUE TITLE
Download needs filename.txt

### ISSUE THREAD

**Issue by aaronmaynard** [aaronmaynard/Skyrim-Perk-Utility#5]
First of all, 
Thank you for your help ❤️

### The Issue

Currently when the user downloads the file in their desired browser, the file will show as "Download" (such as in Firefox). In order to run this script in the game they will first need to add a file extension, either .bat or .txt. This needs to be changed to show "addperk.txt" when initializing the download. 

Your task is to fix the "Download" filename on the webpage, which you can view [HERE](https://aaronmaynard.github.io/Skyrim-Perk-Utility/ "Skyrim Perk Utility").

    $('#download-addperks').click(function() {
      return window.open("data:application/octet-stream," + (encodeURI(getAddPerksCode())));
    });

This code is located in [docs/js/app.js](https://github.com/aaronmaynard/Skyrim-Perk-Utility/blob/master/docs/js/apps) 

I would start by checking on how to generate downloads with html and Javascript. Such an example would be [this one](https://exceptionshub.com/using-html5javascript-to-generate-and-save-a-file.html/Amp "ExceptionsHub") 

### Contributing:

-  Comment in this issue that you would like to do it.
-  Open the Skyrim-Perk-Utility GitHub page and click the ★ Star and then ⑂ Fork buttons.
-  Once you've made sure all your changes work correctly and committed all your changes,
-  Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/Skyrim-Perk-Utility) and create a pull request for your changes.
-  Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #4) 
-  Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community.
If you need any help, feel free to ask below. We are always happy to help 😄

**Comment by AlexanderInsulin** [comment]
I'm want to do it

**Comment by aaronmaynard** [comment]
Fantastic! 💯
