### ISSUE TITLE
Remove HTML from homepage

### ISSUE THREAD

**Issue by aaronmaynard** [aaronmaynard/Skyrim-Perk-Utility#7]
## first-timers-only

This issue is tagged :octocat: first-timers-only. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Thank you for your help ❤️

Your task is to remove the notice on the footer of the webpage, which you can view [HERE](https://aaronmaynard.github.io/Skyrim-Perk-Utility/ "Skyrim Perk Utility").  We are removing this because the related issue has been resolved.

Just remove the notice in the [docs/index.html](https://github.com/aaronmaynard/Skyrim-Perk-Utility/tree/master/docs) in the <b>footer</b> section.

    <span style="color:red">Notice: </span><span>The script will show as "Download" becuase .bat files are not accepted through some browners.  You can change the file extension to .txt</span>

### Contributing:

-  Comment in this issue that you would like to do it.
-  Open the Skyrim-Perk-Utility GitHub page and click the ★ Star and then ⑂ Fork buttons.
-  Once you've made sure all your changes work correctly and committed all your changes,
-  Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/Skyrim-Perk-Utility) and create a pull request for your changes.
-  Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #7)
-  Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community.
If you need any help, feel free to ask below. We are always happy to help 😄

**Comment by georgepampalis** [comment]
Hello there! I just started learning how to use GitHub, and I would like to use this issue as my first pull request (other than a hello-world GitHub tutorial).

Could I have a go at it?

**Comment by aaronmaynard** [comment]
@georgepampalis Go for it! 👍

**Comment by georgepampalis** [comment]
Did I do everything correctly?
