### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by aaronmaynard** [aaronmaynard/Skyrim-Perk-Utility#8]
## first-timers-only

This issue is tagged :octocat: first-timers-only. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Thank you for your help ❤️

### Issue:

Your task is to add a Code of Conduct to the repository documentation. Take the template code of conduct from [contributor-covenant.org](https://www.contributor-covenant.org/version/1/4/code-of-conduct.md) and replace [INSERT EMAIL ADDRESS] under enforcement with "atm2770@gmail.com".  Then submit a pull request.  Simple as that! It should be labeled CODE_OF_CONDUCT.md

### Contributing:

-  Comment in this issue that you would like to do it.
-  Open the Skyrim-Perk-Utility GitHub page and click the ★ Star and then ⑂ Fork buttons.
-  Once you've made sure all your changes work correctly and committed all your changes,
-  Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/Skyrim-Perk-Utility) and create a pull request for your changes.
-  Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #8)
-  Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community.
If you need any help, feel free to ask below. We are always happy to help 😄

**Comment by vaibssingh** [comment]
I would like to do it.
