### ISSUE TITLE
Add Ordinator Mod Functionality

### ISSUE THREAD

**Issue by TheRealJohnLaRoche** [aaronmaynard/Skyrim-Perk-Utility#9]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request

**Description**:

Add functionality support for the Skyrim mod Ordinator.

**Expected Behavior**:

The project can work the exact same way, just have an alternate version for those with the Ordinator - Perks of Skyrim mod.  Over 1mil people are using this mod, which can be seen from Nexus

**Actual Behavior**:

There Currently is no support for this mod.

**Steps to Reproduce**:

If relevant, please include screenshots and logs.
Not Applicable

**Screenshots (if any)**:

**Would you like to work on this issue?**
- [ ] Yes
- [x] No

**Comment by aaronmaynard** [comment]
A project has been created or this issue.  It will remain open as reference.
